### ISSUE TITLE
Linux seg fault when retrieving strings with unicode control characters

### ISSUE THREAD

**Issue by notsentient** [Microsoft/msphpsql#142]
## Description

Ran into this seg fault while running a php ETL job that executes several thousand SQL select queries.
The query causing it outputs a bunch of names and one of them includes the control character [\u009d](http://www.charbase.com/009d-unicode-operating-system-command).

I believe this issue is a msodbcsql issue as it's reproducible with sqlcmd.
## sqlcmd to reproduce

`deploy@test01:~$ sqlcmd -S 127.0.01 -e -d tempdb -U test -P test -Q $'SELECT \'Jonathan\' UNION ALL SELECT \'Daniel\' UNION ALL SELECT \'Jeffrey\' UNION ALL SELECT \'string\u009d\''`
**Note:** Original query did not contain unions, only using them to simulate multiple rows.
## Environment

**PHP** `PHP 7.0.10 (cli) (built: Sep  1 2016 10:36:48) ( ZTS ) Zend Engine v3.0.0`
**sqlsrv** `4.0.3-Linux`
**Linux** `4.4.0-28-generic x86_64 Ubuntu 16.04.1 LTS`
**ODBC** 

```
[ODBC Driver 13 for SQL Server]
Description=Microsoft ODBC Driver 13 for SQL Server
Driver=/opt/microsoft/msodbcsql/lib64/libmsodbcsql-13.0.so.0.0
Threading=1
UsageCount=2
```

Built PHP and sqlsrv extension from source using the [tutorial](https://github.com/Azure/msphpsql/blob/PHP-7.0-Linux/LinuxTutorial.md)
## Stack trace from php cli

```
Program received signal SIGSEGV, Segmentation fault.
__memcpy_sse2_unaligned () at ../sysdeps/x86_64/multiarch/memcpy-sse2-unaligned.S:38
38      ../sysdeps/x86_64/multiarch/memcpy-sse2-unaligned.S: No such file or directory.
(gdb)
(gdb) bt
#0  __memcpy_sse2_unaligned () at ../sysdeps/x86_64/multiarch/memcpy-sse2-unaligned.S:38
#1  0x00007fffeda69099 in ?? () from /opt/microsoft/msodbcsql/lib64/libmsodbcsql-13.0.so.0.0
#2  0x00007fffeda6ba53 in ?? () from /opt/microsoft/msodbcsql/lib64/libmsodbcsql-13.0.so.0.0
#3  0x00007fffedac150e in ?? () from /opt/microsoft/msodbcsql/lib64/libmsodbcsql-13.0.so.0.0
#4  0x00007ffff6bbbbf7 in SQLGetData (statement_handle=0x16c9530, column_number=<optimized out>, target_type=<optimized out>, target_value=0x7fffe968eaf0, buffer_length=102, strlen_or_ind=0x7fffffff9e90) at SQLGetData.c:443
#5  0x00007fffee7d2162 in core::SQLGetData(sqlsrv_stmt*, unsigned short, short, void*, long, long*, bool) () from /usr/lib/php/extensions/no-debug-zts-20151012/sqlsrv.so
#6  0x00007fffee7cdcd7 in sqlsrv_odbc_result_set::get_data(unsigned short, short, void*, long, long*, bool) () from /usr/lib/php/extensions/no-debug-zts-20151012/sqlsrv.so
#7  0x00007fffee7c58b6 in (anonymous namespace)::get_field_as_string(sqlsrv_stmt*, unsigned short, sqlsrv_phptype, void*&, long*) () from /usr/lib/php/extensions/no-debug-zts-20151012/sqlsrv.so
#8  0x00007fffee7c386b in (anonymous namespace)::core_get_field_common(sqlsrv_stmt*, unsigned short, sqlsrv_phptype, void*&, long*) () from /usr/lib/php/extensions/no-debug-zts-20151012/sqlsrv.so
#9  0x00007fffee7c1c6f in core_sqlsrv_get_field(sqlsrv_stmt*, unsigned short, sqlsrv_phptype, bool, void*&, long*, bool, SQLSRV_PHPTYPE*) () from /usr/lib/php/extensions/no-debug-zts-20151012/sqlsrv.so
#10 0x00007fffee7b4d12 in (anonymous namespace)::fetch_fields_common(ss_sqlsrv_stmt*, long, _zval_struct&, bool) () from /usr/lib/php/extensions/no-debug-zts-20151012/sqlsrv.so
#11 0x00007fffee7b08fe in zif_sqlsrv_fetch_array(_zend_execute_data*, _zval_struct*) () from /usr/lib/php/extensions/no-debug-zts-20151012/sqlsrv.so
#12 0x000000000087e5f2 in ZEND_DO_FCALL_SPEC_HANDLER () at /tmp/php/php-src/Zend/zend_vm_execute.h:842
#13 0x0000000000832feb in execute_ex (ex=<optimized out>) at /tmp/php/php-src/Zend/zend_vm_execute.h:414
#14 0x000000000065a9d2 in pthreads_execute_ex (data=<optimized out>) at /tmp/php/php-src/ext/pthreads/php_pthreads.c:143
#15 0x000000000087e104 in ZEND_DO_FCALL_SPEC_HANDLER () at /tmp/php/php-src/Zend/zend_vm_execute.h:800
#16 0x0000000000832feb in execute_ex (ex=<optimized out>) at /tmp/php/php-src/Zend/zend_vm_execute.h:414
#17 0x000000000065a9d2 in pthreads_execute_ex (data=<optimized out>) at /tmp/php/php-src/ext/pthreads/php_pthreads.c:143
#18 0x000000000087e104 in ZEND_DO_FCALL_SPEC_HANDLER () at /tmp/php/php-src/Zend/zend_vm_execute.h:800
#19 0x0000000000832feb in execute_ex (ex=<optimized out>) at /tmp/php/php-src/Zend/zend_vm_execute.h:414
#20 0x000000000065a9d2 in pthreads_execute_ex (data=<optimized out>) at /tmp/php/php-src/ext/pthreads/php_pthreads.c:143
#21 0x000000000087e104 in ZEND_DO_FCALL_SPEC_HANDLER () at /tmp/php/php-src/Zend/zend_vm_execute.h:800
#22 0x0000000000832feb in execute_ex (ex=<optimized out>) at /tmp/php/php-src/Zend/zend_vm_execute.h:414
#23 0x000000000065a9d2 in pthreads_execute_ex (data=<optimized out>) at /tmp/php/php-src/ext/pthreads/php_pthreads.c:143
#24 0x000000000087e104 in ZEND_DO_FCALL_SPEC_HANDLER () at /tmp/php/php-src/Zend/zend_vm_execute.h:800
#25 0x0000000000832feb in execute_ex (ex=<optimized out>) at /tmp/php/php-src/Zend/zend_vm_execute.h:414
#26 0x000000000065a9d2 in pthreads_execute_ex (data=<optimized out>) at /tmp/php/php-src/ext/pthreads/php_pthreads.c:143
#27 0x000000000087e104 in ZEND_DO_FCALL_SPEC_HANDLER () at /tmp/php/php-src/Zend/zend_vm_execute.h:800
#28 0x0000000000832feb in execute_ex (ex=<optimized out>) at /tmp/php/php-src/Zend/zend_vm_execute.h:414
#29 0x000000000065a9d2 in pthreads_execute_ex (data=<optimized out>) at /tmp/php/php-src/ext/pthreads/php_pthreads.c:143
#30 0x000000000087e104 in ZEND_DO_FCALL_SPEC_HANDLER () at /tmp/php/php-src/Zend/zend_vm_execute.h:800
#31 0x0000000000832feb in execute_ex (ex=<optimized out>) at /tmp/php/php-src/Zend/zend_vm_execute.h:414
#32 0x000000000065a9d2 in pthreads_execute_ex (data=<optimized out>) at /tmp/php/php-src/ext/pthreads/php_pthreads.c:143
#33 0x000000000087e104 in ZEND_DO_FCALL_SPEC_HANDLER () at /tmp/php/php-src/Zend/zend_vm_execute.h:800
#34 0x0000000000832feb in execute_ex (ex=<optimized out>) at /tmp/php/php-src/Zend/zend_vm_execute.h:414
#35 0x000000000065a9d2 in pthreads_execute_ex (data=<optimized out>) at /tmp/php/php-src/ext/pthreads/php_pthreads.c:143
#36 0x000000000087e104 in ZEND_DO_FCALL_SPEC_HANDLER () at /tmp/php/php-src/Zend/zend_vm_execute.h:800
#37 0x0000000000832feb in execute_ex (ex=<optimized out>) at /tmp/php/php-src/Zend/zend_vm_execute.h:414
#38 0x000000000065a9d2 in pthreads_execute_ex (data=<optimized out>) at /tmp/php/php-src/ext/pthreads/php_pthreads.c:143
#39 0x000000000087e104 in ZEND_DO_FCALL_SPEC_HANDLER () at /tmp/php/php-src/Zend/zend_vm_execute.h:800
#40 0x0000000000832feb in execute_ex (ex=<optimized out>) at /tmp/php/php-src/Zend/zend_vm_execute.h:414
#41 0x000000000065a9d2 in pthreads_execute_ex (data=<optimized out>) at /tmp/php/php-src/ext/pthreads/php_pthreads.c:143
#42 0x000000000087e104 in ZEND_DO_FCALL_SPEC_HANDLER () at /tmp/php/php-src/Zend/zend_vm_execute.h:800
#43 0x0000000000832feb in execute_ex (ex=<optimized out>) at /tmp/php/php-src/Zend/zend_vm_execute.h:414
#44 0x000000000065a9d2 in pthreads_execute_ex (data=<optimized out>) at /tmp/php/php-src/ext/pthreads/php_pthreads.c:143
#45 0x000000000087e104 in ZEND_DO_FCALL_SPEC_HANDLER () at /tmp/php/php-src/Zend/zend_vm_execute.h:800
#46 0x0000000000832feb in execute_ex (ex=<optimized out>) at /tmp/php/php-src/Zend/zend_vm_execute.h:414
#47 0x000000000065a9d2 in pthreads_execute_ex (data=<optimized out>) at /tmp/php/php-src/ext/pthreads/php_pthreads.c:143
#48 0x000000000087e104 in ZEND_DO_FCALL_SPEC_HANDLER () at /tmp/php/php-src/Zend/zend_vm_execute.h:800
#49 0x0000000000832feb in execute_ex (ex=<optimized out>) at /tmp/php/php-src/Zend/zend_vm_execute.h:414
#50 0x000000000065a9d2 in pthreads_execute_ex (data=<optimized out>) at /tmp/php/php-src/ext/pthreads/php_pthreads.c:143
#51 0x000000000087e104 in ZEND_DO_FCALL_SPEC_HANDLER () at /tmp/php/php-src/Zend/zend_vm_execute.h:800
#52 0x0000000000832feb in execute_ex (ex=<optimized out>) at /tmp/php/php-src/Zend/zend_vm_execute.h:414
#53 0x000000000065a9d2 in pthreads_execute_ex (data=<optimized out>) at /tmp/php/php-src/ext/pthreads/php_pthreads.c:143
#54 0x000000000087e104 in ZEND_DO_FCALL_SPEC_HANDLER () at /tmp/php/php-src/Zend/zend_vm_execute.h:800
#55 0x0000000000832feb in execute_ex (ex=<optimized out>) at /tmp/php/php-src/Zend/zend_vm_execute.h:414
#56 0x000000000065a9d2 in pthreads_execute_ex (data=<optimized out>) at /tmp/php/php-src/ext/pthreads/php_pthreads.c:143
#57 0x000000000087e104 in ZEND_DO_FCALL_SPEC_HANDLER () at /tmp/php/php-src/Zend/zend_vm_execute.h:800
#58 0x0000000000832feb in execute_ex (ex=<optimized out>) at /tmp/php/php-src/Zend/zend_vm_execute.h:414
#59 0x000000000065a9d2 in pthreads_execute_ex (data=<optimized out>) at /tmp/php/php-src/ext/pthreads/php_pthreads.c:143
#60 0x000000000087e104 in ZEND_DO_FCALL_SPEC_HANDLER () at /tmp/php/php-src/Zend/zend_vm_execute.h:800
#61 0x0000000000832feb in execute_ex (ex=<optimized out>) at /tmp/php/php-src/Zend/zend_vm_execute.h:414
---Type <return> to continue, or q <return> to quit---
#62 0x000000000065a9d2 in pthreads_execute_ex (data=<optimized out>) at /tmp/php/php-src/ext/pthreads/php_pthreads.c:143
#63 0x000000000088f429 in zend_execute (op_array=<optimized out>, return_value=<optimized out>) at /tmp/php/php-src/Zend/zend_vm_execute.h:458
#64 0x00000000007ee907 in zend_execute_scripts (type=type@entry=8, retval=retval@entry=0x0, file_count=file_count@entry=3) at /tmp/php/php-src/Zend/zend.c:1427
#65 0x0000000000780138 in php_execute_script (primary_file=primary_file@entry=0x7fffffffd200) at /tmp/php/php-src/main/main.c:2494
#66 0x0000000000891334 in do_cli (argc=4, argv=0x115ae20) at /tmp/php/php-src/sapi/cli/php_cli.c:974
#67 0x0000000000438c52 in main (argc=4, argv=0x115ae20) at /tmp/php/php-src/sapi/cli/php_cli.c:1344
```

**Comment by meet-bhagdev** [comment]
@notsentient Thanks for the detailed repro. We are looking into this 👍

**Comment by meet-bhagdev** [comment]
@notsentient sqlcmd query seems to have a small mistake: it shoud be sqlcmd -S 127.0.0.1, instead of sqlcmd -S 127.0.01. Can you check that for us?

**Comment by meet-bhagdev** [comment]
Also are what version/environment are you running for SQL Server?

**Comment by notsentient** [comment]
Hey meet, sorry, that's just a typo from me replacing the actual IP of the server.

I've tested in on SQL Server 2014 and SQL Server 2016 with same results.

**Comment by meet-bhagdev** [comment]
@notsentient we found the bug in the ODBC Driver and are fixing it. Stay tuned :+1:

**Comment by meet-bhagdev** [comment]
@notsentient This issue should be fixed with the latest ODBC Driver. You can download it from here: https://github.com/Microsoft/msphpsql/tree/PHP-7.0-Linux#step-2-install--pre-requisites
