### ISSUE TITLE
MAC(version 10.11.3) : odbcinst: SQLInstallDriverEx failed with Invalid install path. 

### ISSUE THREAD

**Issue by vijayaratha** [Microsoft/msphpsql#489]
I tried to install mssql driver to MAC for my PH/Laravel application.

When I try following;
`#brew install microsoft/msodbcsql/msodbcsql 
`
I get following issue;

```
==> Installing msodbcsql from microsoft/msodbcsql
==> Using the sandbox
==> Downloading http://download.microsoft.com/download/4/9/5/495639C0-79E4-45A7-B65A-B264071C3D9A/msodbcsql-13.1.9.0.tar.gz
Already downloaded: /Users/ratha/Library/Caches/Homebrew/msodbcsql-13.1.9.0.tar.gz
The license terms for this product can be downloaded from
https://aka.ms/odbc131eula and found in
/usr/local/share/doc/msodbcsql/LICENSE.txt . By entering 'YES',
you indicate that you accept the license terms.

Do you accept the license terms? (Enter YES or NO)
YES
==> odbcinst -u -d -n "ODBC Driver 13 for SQL Server"
==> odbcinst -i -d -f ./odbcinst.ini
Last 15 lines from /Users/ratha/Library/Logs/Homebrew/msodbcsql/02.odbcinst.ini:
2017-08-03 14:58:01 +1000

odbcinst -i -d -f ./odbcinst.ini

odbcinst: SQLInstallDriverEx failed with Invalid install path.

If reporting this issue please do so to (not Homebrew/brew or Homebrew/core):
microsoft/msodbcsql

/usr/local/Homebrew/Library/Homebrew/utils/github.rb:226:in `raise_api_error': curl failed!  (GitHub::Error)
curl: (22) The requested URL returned error: 422 Unprocessable Entity
curl: (3) <url> malformed
	from /usr/local/Homebrew/Library/Homebrew/utils/github.rb:184:in `open'
	from /usr/local/Homebrew/Library/Homebrew/utils/github.rb:233:in `issues_matching'
	from /usr/local/Homebrew/Library/Homebrew/utils/github.rb:272:in `issues_for_formula'
	from /usr/local/Homebrew/Library/Homebrew/exceptions.rb:369:in `fetch_issues'
	from /usr/local/Homebrew/Library/Homebrew/exceptions.rb:365:in `issues'
	from /usr/local/Homebrew/Library/Homebrew/exceptions.rb:419:in `dump'
	from /usr/local/Homebrew/Library/Homebrew/brew.rb:133:in `rescue in <main>'
	from /usr/local/Homebrew/Library/Homebrew/brew.rb:26:in `<main>'
```
SO query

https://stackoverflow.com/questions/45474305/pdoexception-file-not-found-for-mssql-odbc/45474492?noredirect=1#comment77910465_45474492

**Comment by Hadis-Fard** [comment]
Can you try the steps in [README](https://github.com/Microsoft/msphpsql)?

```
brew tap microsoft/msodbcsql https://github.com/Microsoft/homebrew-mssql-release
brew update
brew install msodbcsql
brew install mssql-tools
brew install autoconf
```

**Comment by Hadis-Fard** [comment]
@vijayaratha This issue is caused changes in homebrew, please see #491

**Comment by Hadis-Fard** [comment]
@vijayaratha can you confirm whether your issue is fixed by `--no-sandbox`?

**Comment by vijayaratha** [comment]
@Hadis-Fard  Yes That fixed the installation issue of msodbcsql driver in MAC.

**Comment by kenorb** [comment]
Adding `--no-sandbox` didn't solve the issue for me.

The solution was to create `~/.odbcinst.ini` file:

    printf "[ODBC Driver 13 for SQL Server]\nDescription=Microsoft ODBC Driver 13 for SQL Server\nDriver=/usr/local/lib/libmsodbcsql.13.dylib\n" >> ~/.odbcinst.ini
